### ISSUE TITLE
How about adding 'daily' to make curtain's action in routine?

### ISSUE THREAD

**Issue by IoriOikawa** [b1f6c1c4/e-curtain#1]
Otherwise, I'll sleep outside, or you'll be pissed off with alarm ring bells every morning.
What do you think?

**Comment by b1f6c1c4** [comment]
Changes applied. Wait several days to see if its stable.

**Comment by b1f6c1c4** [comment]
@IoriOikawa Check and see if we can close the issue.

**Comment by b1f6c1c4** [comment]
@IoriOikawa

**Comment by IoriOikawa** [comment]
Seems that we are good for now.
